##server configuration
server:
  port: 8180
  servlet:
    contextPath: /dnxt/swagger

##spring configuration
spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: dnxt
    password: 123456
